config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  TYPES = %w{ new fix update }

  after_initialize :set_defaults

  validates :announcement_type, :description, :name, :published_at, presence: true
  validates :announcement_type, inclusion: { in: TYPES }

  def set_defaults
    self.published_at      ||= Time.zone.now
    self.announcement_type ||= TYPES.first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  Devise.omniauth_configs.keys.each do |provider|
    scope provider, ->{ where(provider: provider) }
  end

  def client
    send("#{provider}_client")
  end

  def expired?
    expires_at? && expires_at <= Time.zone.now
  end

  def access_token
    send("#{provider}_refresh_token!", super) if expired?
    super
  end


  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_app_id
      config.consumer_secret     = Rails.application.secrets.twitter_app_secret
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def twitter_refresh_token!(token); end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :masqueradable, :database_authenticatable, :registerable, :trackable, :recoverable, :rememberable, :validatable, :omniauthable

  has_one_attached :avatar
  has_person_name

  has_many :notifications, as: :recipient
  has_many :services
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :mark_as_read, if: :user_signed_in?

  def index
    @announcements = Announcement.order(published_at: :desc)
  end

  private

    def mark_as_read
      current_user.update(announcements_last_read_at: Time.zone.now)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :masquerade_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    # Convert the database records to Noticed notification instances so we can use helper methods
    @notifications = current_user.notifications.map(&:to_notification)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_action :set_service
    before_action :set_user

    attr_reader :service, :user

    def facebook
      handle_auth "Facebook"
    end

    def twitter
      handle_auth "Twitter"
    end

    def github
      handle_auth "Github"
    end

    private

    def handle_auth(kind)
      if service.present?
        service.update(service_attrs)
      else
        user.services.create(service_attrs)
      end

      if user_signed_in?
        flash[:notice] = "Your #{kind} account was connected."
        redirect_to edit_user_registration_path
      else
        sign_in_and_redirect user, event: :authentication
        set_flash_message :notice, :success, kind: kind
      end
    end

    def auth
      request.env['omniauth.auth']
    end

    def set_service
      @service = Service.where(provider: auth.provider, uid: auth.uid).first
    end

    def set_user
      if user_signed_in?
        @user = current_user
      elsif service.present?
        @user = service.user
      elsif User.where(email: auth.info.email).any?
        # 5. User is logged out and they login to a new account which doesn't match their old one
        flash[:alert] = "An account with this email already exists. Please sign in with that account before connecting your #{auth.provider.titleize} account."
        redirect_to new_user_session_path
      else
        @user = create_user
      end
    end

    def service_attrs
      expires_at = auth.credentials.expires_at.present? ? Time.at(auth.credentials.expires_at) : nil
      {
          provider: auth.provider,
          uid: auth.uid,
          expires_at: expires_at,
          access_token: auth.credentials.token,
          access_token_secret: auth.credentials.secret,
      }
    end

    def create_user
      User.create(
        email: auth.info.email,
        #name: auth.info.name,
        password: Devise.friendly_token[0,20]
      )
    end

  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def unread_announcements(user)
    last_announcement = Announcement.order(published_at: :desc).first
    return if last_announcement.nil?

    # Highlight announcements for anyone not logged in, cuz tempting
    if user.nil? || user.announcements_last_read_at.nil? || user.announcements_last_read_at < last_announcement.published_at
      "unread-announcements"
    end
  end

  def announcement_class(type)
    {
      "new" => "text-success",
      "update" => "text-warning",
      "fix" => "text-danger",
    }.fetch(type, "text-success")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_path(object, options = {})
    size = options[:size] || 180
    default_image = options[:default] || "mp"
    base_url =  "https://secure.gravatar.com/avatar"
    base_url_params = "?s=#{size}&d=#{default_image}"

    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size, { gravity: 'Center' }])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
      "#{base_url}/#{gravatar_id}#{base_url_params}"
    else
      "#{base_url}/00000000000000000000000000000000#{base_url_params}"
    end
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-primary"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/views/announcements/index.html.erb
<h1>What's New</h1>

<div class="card">
  <div class="card-body">
    <% @announcements.each_with_index do |announcement, index| %>
      <% if index != 0 %>
        <div class="row"><div class="col"><hr /></div></div>
      <% end %>

      <div class="row announcement" id="<%= dom_id(announcement) %>">
        <div class="col-sm-1 text-center">
          <%= link_to announcements_path(anchor: dom_id(announcement)) do %>
            <strong><%= announcement.published_at.strftime("%b %d") %></strong>
          <% end %>
        </div>
        <div class="col">
          <strong class="<%= announcement_class(announcement.announcement_type) %>"><%= announcement.announcement_type.titleize %>:</strong>
          <strong><%= announcement.name %></strong>
          <%= simple_format announcement.description %>
        </div>
      </div>
    <% end %>

    <% if @announcements.empty? %>
      <div>Exciting stuff coming very soon!</div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="center jumbotron mt-5 mb-5">
  <div class="container">
    <div class="centerfy">
      <h1 class="mt-3">Welcome to Stimulus SaaS!</h1>
      <p class="lead">A Ruby On Rails Template with preinstalled often needed features ready to build
       </p>
    </div>
  </div>
</div>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>

    <div class="container mx-auto">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/madmin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="ROBOTS" content="NOODP">
    <meta name="viewport" content="initial-scale=1">
    <title>
      Madmin: <%= Rails.application.class %>
    </title>
    <link href="https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/@tailwindcss/forms/dist/forms.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/@tailwindcss/typography/dist/typography.min.css" rel="stylesheet" />
    <%= csrf_meta_tags %>

    <%= render "javascript" %>
  </head>
  <body class="prose" style="max-width:none">
    <div class="flex w-full p-4">
      <div id="sidebar" class="w-64 flex-shrink-0">
        <%= render "navigation" -%>
      </div>
      <main class="w-full" role="main">
        <%#= render "flashes" -%>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/madmin/application/_form.html.erb
<%= form_with model: [:madmin, record], url: (record.persisted? ? resource.show_path(record) : resource.index_path), local: true do |form| %>
  <% if form.object.errors.any? %>
    <div class="mb-4 rounded-md text-sm text-red-700 bg-red-100 p-4">
      <div class="mb-2 font-medium leading-5 text-red-800">There was <%= pluralize form.object.errors.full_messages.count, "error" %> with your submission</div>

      <% form.object.errors.full_messages.each do |message| %>
        <div class="ml-4"><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <% resource.attributes.each do |attribute| %>
    <% next if attribute[:field].nil? %>
    <% next unless attribute[:field].visible?(action_name) %>
    <% next unless attribute[:field].visible?(:form) %>

    <% field = attribute[:field] %>

    <div class="mb-4 flex">
      <%= render partial: field.to_partial_path("form"), locals: { field: field, record: record, form: form, resource: resource } %>
    </div>
  <% end %>

  <%= form.submit class: "bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" %>
<% end %>

app/views/madmin/application/_javascript.html.erb
<%= stylesheet_link_tag "https://unpkg.com/flatpickr/dist/flatpickr.min.css", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "https://unpkg.com/trix/dist/trix.css", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "https://unpkg.com/slim-select@1.27.0/dist/slimselect.min.css", "data-turbo-track": "reload" %>

<script type="module">
  import { Application, Controller } from 'https://cdn.skypack.dev/stimulus'
  const application = Application.start()

  import stimulusFlatpickr from 'https://cdn.skypack.dev/stimulus-flatpickr'
  application.register("flatpickr", stimulusFlatpickr)

  import stimulusSlimselect from 'https://cdn.skypack.dev/stimulus-slimselect'
  application.register("slimselect", stimulusSlimselect)

  import Rails from 'https://cdn.skypack.dev/@rails/ujs@<%= npm_rails_version %>'
  import * as ActiveStorage from 'https://cdn.skypack.dev/@rails/activestorage@<%= npm_rails_version %>'
  import 'https://cdn.skypack.dev/trix'
  import 'https://cdn.skypack.dev/@rails/actiontext@<%= npm_rails_version %>'

  if (!window._rails_loaded) { Rails.start() }
  ActiveStorage.start()

  import * as Turbo from "https://cdn.skypack.dev/@hotwired/turbo"

  (() => {
    application.register('nested-form', class extends Controller {
      static get targets() {
        return [ "links", "template" ]
      }

      connect() {
        this.wrapperClass = this.data.get("wrapperClass") || "nested-fields"
      }

      add_association(event) {
        event.preventDefault()

        var content = this.templateTarget.innerHTML.replace(/NEW_RECORD/g, new Date().getTime())
        this.linksTarget.insertAdjacentHTML('beforebegin', content)
      }

      remove_association(event) {
        event.preventDefault()

        let wrapper = event.target.closest("." + this.wrapperClass)

        // New records are simply removed from the page
        if (wrapper.dataset.newRecord == "true") {
          wrapper.remove()

        // Existing records are hidden and flagged for deletion
        } else {
          wrapper.querySelector("input[name*='_destroy']").value = 1
          wrapper.style.display = 'none'
        }
      }
    })
  })()
</script>

app/views/madmin/application/_navigation.html.erb
<div class="text-sm">
  <%= link_to "← Back to App", main_app.root_url, class: "block p-1", data: { turbo: false } if main_app.respond_to?(:root_url) %>
  <% Madmin.resources.each do |resource| %>
    <%= link_to resource.friendly_name.pluralize, resource.index_path, class: "block p-1" %>
  <% end %>
</div>

app/views/madmin/application/edit.html.erb
<h1><%= link_to resource.friendly_name.pluralize, resource.index_path %> / Edit <%= resource.friendly_name %> #<%= @record.id %></h1>

<%= render partial: "form", locals: { record: @record, resource: resource } %>

app/views/madmin/application/index.html.erb
<div class="flex justify-between">
  <h1><%= resource.friendly_name.pluralize %></h1>
  <%= link_to "New #{resource.friendly_name}", resource.new_path %>
</div>

<div>
  <% if resource.scopes.any? %>
    <%= link_to "All", resource.index_path %>
  <% end %>

  <% resource.scopes.each do |scope| %>
    <%= link_to scope.to_s.humanize, resource.index_path(scope: scope) %>
  <% end %>
</div>

<table class="table-auto">
  <thead>
    <tr>
      <% resource.attributes.each do |attribute| %>
        <% next if attribute[:field].nil? %>
        <% next unless attribute[:field].visible?(action_name) %>

        <th><%= sortable attribute[:name], attribute[:name].to_s.titleize %></th>
      <% end %>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <% resource.attributes.each do |attribute| %>
          <% next if attribute[:field].nil? %>
          <% next unless attribute[:field].visible?(action_name) %>

          <% field = attribute[:field] %>

          <td><%= render partial: field.to_partial_path("index"), locals: { field: field, record: record } %></td>
        <% end %>

        <td><%= link_to "View", resource.show_path(record) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/madmin/application/new.html.erb
<h1><%= link_to resource.friendly_name.pluralize, resource.index_path %> / New <%= resource.friendly_name %></h1>

<%= render partial: "form", locals: { record: @record, resource: resource } %>

app/views/madmin/application/show.html.erb
<div class="flex justify-between">
  <h1><%= link_to resource.friendly_name.pluralize, resource.index_path %> / <%= resource.model.name.singularize %> #<%= @record.id %></h1>

  <div class="flex px-4">
    <%= link_to "Edit", resource.edit_path(@record), class: "mr-2" %>
    <%= button_to "Delete", resource.show_path(@record), method: :delete, data: { confirm: "Are you sure?" }, class: "inline-block" %>
  </div>
</div>

<% resource.attributes.each do |attribute| %>
  <% next if attribute[:field].nil? %>
  <% next unless attribute[:field].visible?(action_name) %>
  <% field = attribute[:field] %>

  <div class="flex py-2">
    <div class="w-32 flex-shrink-0 text-gray-700 uppercase tracking-wide text-sm">
      <%= field.attribute_name.to_s.titleize %>
    </div>

    <div>
      <%= render partial: field.to_partial_path("show"), locals: { field: field, record: @record } %>
    </div>
  </div>
<% end %>

app/views/notifications/index.html.erb
<h1>Notifications</h1>

<ul>
  <% @notifications.each do |notification| %>
    <%# Customize your notification format here. We typically recommend a `message` and `url` method on the Notification classes. %>
    <%#= link_to notification.message, notification.url %>

    <li><%= notification.params %></li>
  <% end %>
</ul>

app/views/shared/_footer.html.erb
 <footer class="text-center text-white mt-4" style="background:linear-gradient(90deg, #667eea 0%,#764ba2 100% );">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register on Stimulus SaaS for free</span>
           <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-outline-light btn-rounded" %>
         
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://xhostcom.com/">Paul Anthony McGowan</a>
    </div>
    <!-- Copyright -->
  </footer>

app/views/shared/_head.html.erb
<title>Rails Stimulus SaaS</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
 <%= action_cable_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container mx-auto">
    <%= link_to "Rails Stimulus SaaS", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to notifications_path, class: "nav-link" do %>
            <span><i class="far fa-bell" aria-hidden="true"></i></span>
          <% end %>
         </li>

          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:madmin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<div class="container mx-auto">
  <% flash.each do |msg_type, message| %>
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>